######################################################################
###Use LIMMA to Identifiy DEGs #######################################
######################################################################
#Uses the LIMMA Files generated by F1_1_PrepQuantFilesForLimma.R script 


#### Set global paramaters
options(scipen=20)
Root_Directory<-"//cmvm.datastore.ed.ac.uk/CMVM/scs/groups/rilling2-lab/Rob/Data/NGS_Sequence_Data/R_Analysis_GitHub_I53A"

#target files outlining sample information associated with quantitation files
Sample_Target<-"TargetExon.txt"
Contrasts_Target<-"AnalysisContrasts.txt"
#differential expression analysis paramaters > name to append / adjusted p value cut off / Log2 fold change cut off 
name<-"Expression"
co<-0.01
diff<-1



###Run Script#############################################################
#load libraries
library(limma)
library(Biobase)

#Load sample target file
setwd(Root_Directory)
setwd("Figure_1/Target_Files/")
target<-read.delim(Sample_Target,header=TRUE)

##Create a LIMMA expression object containing all your expression data and annotation   
setwd(Root_Directory)
setwd("Figure_1/Analaysis_Output/Files_For_LIMMA/")
Expr<-read.maimages(files=as.character(unlist(target[,2])), source="generic", names=unlist(target[,4]),verbose=TRUE,columns=list(E="Expression"), other.columns=NULL, annotation=list(ID="Gene_ID",Symbol="name2",Chr="chr",Start="start",End="end",Strand="strand",Length="Length"),green.only=TRUE,sep="\t")

##Normalize the data across samples using quantile normalisation 
ExprBS<-backgroundCorrect(Expr, method="none", offset=0)
ExprNorm <-normalizeBetweenArrays(ExprBS, method="quantile")

##Normalize the data across samples using quantile normalisation 
setwd(Root_Directory)
setwd("Figure_1/Analaysis_Output/")
dir.create("Diff_Analysis")
setwd("Diff_Analysis")


##clustering dendrogram of normalised data
jpeg(filename = paste(name,"Clustering.jpg",sep=""))
Norm <- dist(t(as.matrix((ExprNorm$E),byrow=TRUE)))
plot(hclust(Norm), labels=colnames(ExprNorm$E))
dev.off()



######### Create a LIMMA Fit object
a<-unique(target[,3])
#create design matrix
design<-matrix(data=0,nrow=nrow(target),ncol=length(a))
colnames(design)<-a
for(i in 1:length(a)){
tmp<-grep(paste("^",unique(a[i]),"$",sep=""),target[,3])
design[tmp,i]<-1}
##make fit object
fit<-lmFit(ExprNorm,design)

##Make a summary table from every compariosn in the Contrasts table
Data<-fit$genes



##Run differential expression analysis based on the paramaters above and the contrasts specificed above
##read in contarsts and run the analysis 
setwd(Root_Directory)
setwd("Figure_1/Target_Files/")
Contrasts<-read.delim("AnalysisContrasts.txt")


setwd(Root_Directory)
setwd("Figure_1/Analaysis_Output/Diff_Analysis")


for(k in 1:nrow(Contrasts)){
x<-as.character(Contrasts[k,1])
name<-Contrasts[k,2]
cont.matrix <- makeContrasts(x,levels=colnames(design))
fit2 <- contrasts.fit(fit, cont.matrix)
fit2 <- eBayes(fit2)
TT<-topTable(fit2,adjust.method="BH",number=nrow(fit2),sort.by="none")

###########################tiff
tiff(paste(name,".tiff",sep=""),width=7,height=7,units="in",res=150)
par(mar=c(5.1, 5.1, 4.1, 2.1), bty="n")
par(xaxt="n",yaxt="n",col.axis="white")
smoothScatter(TT$AveExpr,TT$logFC,xlab="",ylab="",main="",cex.main=2,cex.lab=2,ylim=c(-10,10),nbin = 500,bandwidth=c(0.05,0.1),nrpoints = 0, colramp = colorRampPalette(c("white", "black")),xlim=c(0,20))
a<-which((TT$logFC>=diff)&(TT$adj.P.Val<=co))
b<-which((TT$logFC<=(-diff))&(TT$adj.P.Val<=co))
c<-length(unique(TT$Gene_ID[a]))
d<-length(unique(TT$Gene_ID[b]))
e<-length(unique(TT$SystematicName[a]))
f<-length(unique(TT$SystematicName[b]))
points(TT$AveExpr[a],TT$logFC[a],pch=21, bg="#d95f02",cex=0.7)
points(TT$AveExpr[b],TT$logFC[b],pch=21, bg="#7570b3",cex=0.7)
dev.off()

###########################pdf
pdf(paste(name,".pdf",sep=""),useDingbats=FALSE,width=7,height=7)
par(mar=c(5.1, 5.1, 4.1, 2.1), bty="l")
plot(1,1,type="n",col="white",xlab="Mean Expression (Log2)",ylab="Differential Expression (Log2)",main=name,cex.main=2,cex.lab=2,ylim=c(-10,10),xlim=c(0,20),axes=FALSE)
axis(1)
axis(2,at=c(-10,-5,0,5,10))
a<-which((TT$logFC>=diff)&(TT$adj.P.Val<=co))
b<-which((TT$logFC<=(-diff))&(TT$adj.P.Val<=co))
c<-length(unique(TT$Gene_ID[a]))
d<-length(unique(TT$Gene_ID[b]))
e<-length(unique(TT$SystematicName[a]))
f<-length(unique(TT$SystematicName[b]))
points(TT$AveExpr[a],TT$logFC[a],pch=21, bg="#d95f02")
points(TT$AveExpr[b],TT$logFC[b],pch=21, bg="#7570b3")
xl<-sub("-.*","",x)
yl<-sub(".*-","",x)
legend("topright",legend=c(paste("Up in ",xl," = ",length(a)," (",e,")",sep=""),paste("Up in ",yl," = ",length(b)," (",f,")",sep="")),bty="n",cex=0.7)
dev.off()

###add data to table
a<-match(Data$Gene_ID,TT$Gene_ID)
tmp<-TT[a,c(8,9,12)]
colnames(tmp)<-paste(colnames(tmp),"_",name,sep="")
Data<-cbind(Data,tmp)

}
   


##combine values into a master table
a<-match(Data$Gene_ID,fit$genes$Gene_ID)
Data<-cbind(Data,fit$coefficients[a,])

#write out a summary expression table
head(Data)
colnames(Data)[2]<-"Gene_Symbol"
write.table(Data,"SummaryExpression.txt",sep="\t",quote=FALSE,col.names=TRUE,row.names=FALSE)

Summary_Expression<-Data


##rm all objects but Processed and Fit 
rm(list=setdiff(ls(), c("Summary_Expression","Root_Directory")))
setwd(Root_Directory)
setwd("R_Images/")

save.image("1_Summary_Expr_Data.RData")
